// Phase 4 giving — Paystack HTTP client (PRD 06 §3, §7).
//
// The ONLY place that touches Paystack HTTP endpoints lives behind this
// class, and `PaymentService` is the only caller (ARC-03). `fetchImpl` is
// injected (default: global fetch) so tests NEVER hit the live API.
//
// Endpoints verified against current Paystack docs (2026-09-26):
// - Initialize: POST https://api.paystack.co/transaction/initialize
//   (https://paystack.com/docs/payments/accept-payments/)
// - Verify: GET https://api.paystack.co/transaction/verify/:reference
//   (https://paystack.com/docs/payments/verify-payments/)
// - Webhooks: `x-paystack-signature` = HMAC-SHA512 of the RAW body with the
//   secret key (https://paystack.com/docs/payments/webhooks/).
// Behaviour requirements in PRD 06 win over these details if they drift.

import { createHmac, timingSafeEqual } from "node:crypto";

export const PAYSTACK_BASE_URL = "https://api.paystack.co";
export const PAYSTACK_SIGNATURE_HEADER = "x-paystack-signature";

export type FetchImpl = (
  url: string,
  init?: RequestInit,
) => Promise<Response>;

export type InitializeInput = {
  email: string;
  amountKobo: number;
  reference: string;
  callbackUrl?: string;
};

export type InitializeResult = {
  authorizationUrl: string;
  accessCode: string;
  paystackReference: string;
};

export type VerifyResult = {
  /** Paystack transaction status: success | failed | abandoned | ... */
  status: string;
  amountKobo: number;
  currency: string;
  paystackReference: string;
  channel?: string;
  paidAt?: string;
};

export class PaystackError extends Error {
  readonly status: number;
  constructor(message: string, status = 502) {
    super(message);
    this.name = "PaystackError";
    this.status = status;
  }
}

export class PaystackClient {
  private readonly secretKey: string;
  private readonly baseUrl: string;
  private readonly fetchImpl: FetchImpl;

  constructor(opts: {
    secretKey: string;
    baseUrl?: string;
    fetchImpl?: FetchImpl;
  }) {
    if (!opts.secretKey) {
      throw new PaystackError("Paystack secret key is not configured (GIV-13)");
    }
    this.secretKey = opts.secretKey;
    this.baseUrl = (opts.baseUrl ?? PAYSTACK_BASE_URL).replace(/\/+$/, "");
    this.fetchImpl = opts.fetchImpl ?? globalThis.fetch.bind(globalThis);
  }

  private headers(): Record<string, string> {
    return {
      Authorization: `Bearer ${this.secretKey}`,
      "Content-Type": "application/json",
    };
  }

  // GIV-02: amount in kobo (integer), currency NGN. The reference is always
  // server-generated by PaymentService (GIV-01) — never from the browser.
  async initializeTransaction(
    input: InitializeInput,
  ): Promise<InitializeResult> {
    if (!Number.isInteger(input.amountKobo) || input.amountKobo <= 0) {
      throw new PaystackError("amount must be a positive integer kobo (GIV-02)");
    }
    let res: Response;
    try {
      res = await this.fetchImpl(`${this.baseUrl}/transaction/initialize`, {
        method: "POST",
        headers: this.headers(),
        body: JSON.stringify({
          email: input.email,
          amount: input.amountKobo,
          reference: input.reference,
          currency: "NGN",
          ...(input.callbackUrl ? { callback_url: input.callbackUrl } : {}),
        }),
      });
    } catch (e) {
      throw new PaystackError(
        `Paystack initialise unreachable: ${(e as Error).message}`,
      );
    }
    const json = (await res.json().catch(() => null)) as {
      status?: boolean;
      message?: string;
      data?: {
        authorization_url?: string;
        access_code?: string;
        reference?: string;
      };
    } | null;
    if (!res.ok || !json?.status || !json.data?.authorization_url) {
      throw new PaystackError(
        `Paystack initialise failed: ${json?.message ?? `HTTP ${res.status}`} (GIV edge: retry)`,
      );
    }
    return {
      authorizationUrl: json.data.authorization_url,
      accessCode: json.data.access_code ?? "",
      paystackReference: json.data.reference ?? input.reference,
    };
  }

  // Server-to-server verification (GIV-03/04). Returns the raw facts;
  // PaymentService decides the transition.
  async verifyTransaction(reference: string): Promise<VerifyResult> {
    let res: Response;
    try {
      res = await this.fetchImpl(
        `${this.baseUrl}/transaction/verify/${encodeURIComponent(reference)}`,
        { method: "GET", headers: this.headers() },
      );
    } catch (e) {
      throw new PaystackError(
        `Paystack verify unreachable: ${(e as Error).message}`,
      );
    }
    const json = (await res.json().catch(() => null)) as {
      status?: boolean;
      message?: string;
      data?: {
        status?: string;
        reference?: string;
        amount?: number;
        currency?: string;
        channel?: string;
        paid_at?: string;
      };
    } | null;
    if (!res.ok || !json?.status || !json.data) {
      throw new PaystackError(
        `Paystack verify failed: ${json?.message ?? `HTTP ${res.status}`}`,
      );
    }
    return {
      status: json.data.status ?? "unknown",
      amountKobo: Number(json.data.amount ?? NaN),
      currency: json.data.currency ?? "",
      paystackReference: json.data.reference ?? reference,
      channel: json.data.channel,
      paidAt: json.data.paid_at,
    };
  }

  // GIV-05: HMAC-SHA512 of the RAW body vs the `x-paystack-signature`
  // header, constant-time compare. Accepts string or Buffer raw bodies.
  isSignatureValid(
    rawBody: string | Buffer,
    signatureHeader: string | null | undefined,
  ): boolean {
    if (!signatureHeader) return false;
    const expected = createHmac("sha512", this.secretKey)
      .update(rawBody)
      .digest("hex");
    const a = Buffer.from(signatureHeader.trim().toLowerCase(), "utf8");
    const b = Buffer.from(expected.toLowerCase(), "utf8");
    return a.length === b.length && timingSafeEqual(a, b);
  }
}

// Test helper: sign a raw body the way Paystack does (used by routes in
// production for nothing — tests + docs only).
export function signPayload(rawBody: string | Buffer, secretKey: string): string {
  return createHmac("sha512", secretKey).update(rawBody).digest("hex");
}
